### ISSUE TITLE
pyls_ms errors

### ISSUE THREAD

**Issue by habamax** [mattn/vim-lsp-settings#117]
I have successfully installed `pyls_ms` on win 10 (at least there were no errors).

But when I open python file I get following error:

![image](https://user-images.githubusercontent.com/234774/73367917-398ec280-42c1-11ea-94ba-d9cacfdecd7c.png)

and `LspStatus` shows:
![image](https://user-images.githubusercontent.com/234774/73368102-7d81c780-42c1-11ea-87d3-23c166cdef64.png)

after `:e` I get:

![image](https://user-images.githubusercontent.com/234774/73368235-adc96600-42c1-11ea-9a0d-2415dd2ad6ba.png)

PS, thx for adding `pyls_ms`!

**Comment by mattn** [comment]
Could you please try last change?

**Comment by habamax** [comment]
> Could you please try last change?

Tried, the same.

**Comment by mattn** [comment]
Hmm, the command should be "pyls-ms" not "pyls_ms". Please show me `:LspStatus`.

**Comment by habamax** [comment]
![image](https://user-images.githubusercontent.com/234774/73377804-b4130e80-42d0-11ea-8c4e-dcfb3df73ebc.png)

**Comment by habamax** [comment]
![image](https://user-images.githubusercontent.com/234774/73377881-d1e07380-42d0-11ea-9640-869b0df774b4.png)

![image](https://user-images.githubusercontent.com/234774/73377912-db69db80-42d0-11ea-970b-41968d2e8bdc.png)


Let me try to reinstall

**Comment by habamax** [comment]
This is weird... I have deleted `pyls-ms` folder and opened python file in vim:

![image](https://user-images.githubusercontent.com/234774/73378153-356aa100-42d1-11ea-887c-65d634f2f1b9.png)

and lspstatus shows `pyls not running`:
![image](https://user-images.githubusercontent.com/234774/73378199-47e4da80-42d1-11ea-8de5-4dac45c1d2a8.png)

**Comment by habamax** [comment]
Not in neovim though -- It open the file without error. My vim version is 8.2.172

**Comment by habamax** [comment]
But on the other hand pyls-ms still doesn't work in neovim and I get

![image](https://user-images.githubusercontent.com/234774/73378725-21736f00-42d2-11ea-94b5-e1ccd92447db.png)

After trying to type `print` in the buffer

**Comment by mattn** [comment]
What value do you get with `:echo lsp_settings#exec_path('pyls-ms')` ?

**Comment by mattn** [comment]
In your environment, you have two language server for python.

1. pyls
2. pyls-ms

If you prefer pyls-ms, please add `let g:lsp_settings_python = 'pyls-ms'` into your vimrc

**Comment by habamax** [comment]
> If you prefer pyls-ms, please add `let g:lsp_settings_python = 'pyls-ms'` into your vimrc

Yes! It helped!
![image](https://user-images.githubusercontent.com/234774/73383040-b29a1400-42d9-11ea-8e3b-ea148f98900c.png)



> In your environment, you have two language server for python.

But I have uninstalled `pyls` ... and it is not present in `./servers` folder...

**Comment by habamax** [comment]
> 
> 
> What value do you get with `:echo lsp_settings#exec_path('pyls-ms')` ?

    It is C:\Users\maksim.kim\vimfiles\pack\minpac\start\vim-lsp-settings\servers\pyls-ms\pyls-ms.cmd

**Comment by habamax** [comment]
Anyway, thank you very much! It is solved.
