### ISSUE TITLE
Win10: pyls-ms doesn't work

### ISSUE THREAD

**Issue by habamax** [mattn/vim-lsp-settings#132]
Today I have updated plugin and suddenly pyls-ms doesn't start for the same file it worked yesterday https://github.com/mattn/vim-lsp-settings/issues/117#issuecomment-579880958.

Now `LspStatus` doesn't show anything, and none of the commands work.

**Comment by habamax** [comment]
It actually doesn't work for all my installed servers (vimscript, dart, xml).

**Comment by habamax** [comment]
Ok, I have manually cloned the repo and it works for vimscript. Not sure what is happening (usually I update with minpac)

But pyls-ms shows status:
![image](https://user-images.githubusercontent.com/234774/73428194-9fbf2800-4349-11ea-866d-245170eec00f.png)

**Comment by mattn** [comment]
I updated code recently. Please check last commit.

**Comment by habamax** [comment]
> I updated code recently. Please check last commit.


![image](https://user-images.githubusercontent.com/234774/73429671-36411880-434d-11ea-919e-8b56d2ec0f20.png)

**Comment by habamax** [comment]
Log:

```
30.01.2020 10:57:21:["s:on_text_document_did_change()",5]
30.01.2020 10:57:21:["s:send_didchange_queue() will be triggered"]
30.01.2020 10:57:23:["s:on_text_document_did_close()",1]
30.01.2020 10:57:23:["s:on_text_document_did_close()",1]
30.01.2020 10:57:25:["vim-lsp signs enabled"]
30.01.2020 10:57:25:["vim-lsp highlighting enabled (textprop)"]
30.01.2020 10:57:25:["s:on_text_document_did_open()",1,"txt","C:\\Users\\maksim.kim\\scoop\\apps\\vim-nightly\\current",""]
30.01.2020 10:57:27:["s:on_text_document_did_close()",3]
30.01.2020 10:57:28:["lsp#register_server","server registered","pyls-ms"]
30.01.2020 10:57:28:["s:on_text_document_did_open()",1,"python","C:\\Users\\maksim.kim\\scoop\\apps\\vim-nightly\\current","file:///C:/Users/maksim.kim/projects/test_lsp.py"]
30.01.2020 10:57:28:["Starting server","pyls-ms",["C:\\Users\\maksim.kim\\vimfiles\\lsp-servers\\pyls-ms\\pyls-ms.cmd"]]
30.01.2020 10:57:28:[{"response":{"data":{"__data__":"vim-lsp","lsp_id":1,"server_name":"pyls-ms"},"message":"started lsp server successfully"}}]
30.01.2020 10:57:28:["--->",1,"pyls-ms",{"method":"initialize","params":{"rootUri":"file:///C:/Users/maksim.kim/scoop/apps/vim-nightly/current","initializationOptions":{"interpreter":{"properties":{"Version":"3.8.1","UseDefaultDatabase":true,"InterpreterPath":"C:\\Users\\maksim.kim\\AppData\\Local\\Programs\\Python\\Python38\\python.EXE"}},"asyncStartup":true,"displayOptions":{},"analysisUpdates":true},"capabilities":{"workspace":{"configuration":true,"applyEdit":true},"textDocument":{"implementation":{"linkSupport":true},"documentSymbol":{"symbolKind":{"valueSet":[10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,1,2,3,4,5,6,7,8,9]},"hierarchicalDocumentSymbolSupport":false},"semanticHighlightingCapabilities":{"semanticHighlighting":true},"codeAction":{"codeActionLiteralSupport":{"codeActionKind":{"valueSet":["","quickfix","refactor","refactor.extract","refactor.inline","refactor.rewrite","source","source.organizeImports"]}},"dynamicRegistration":false},"completion":{"completionItem":{"snippetSupport":true,"documentationFormat":["plaintext"]},"completionItemKind":{"valueSet":[10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,1,2,3,4,5,6,7,8,9]}},"foldingRange":{"lineFoldingOnly":true},"typeDefinition":{"linkSupport":true},"typeHierarchy":false,"declaration":{"linkSupport":true},"definition":{"linkSupport":true}}},"rootPath":"C:\\Users\\maksim.kim\\scoop\\apps\\vim-nightly\\current","processId":435676,"trace":"off"}}]
30.01.2020 10:57:29:["<---(stderr)",1,"pyls-ms",["Could not execute because the specified command or file was not found.\r","Possible reasons for this include:\r","  * You misspelled a built-in dotnet command.\r","  * You intended to execute a .NET Core program, but dotnet-Microsoft.Python.LanguageServer.dll does not exist.\r","  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.\r",""]]
30.01.2020 10:57:29:["s:on_exit",1,"pyls-ms","exited",1]
30.01.2020 10:57:32:["s:on_text_document_did_close()",3]
30.01.2020 10:57:32:["s:on_text_document_did_close()",1]
```

**Comment by habamax** [comment]
If I run pyls-ms.cmd in powershell it works.

```PS C:\Users\maksim.kim\vimfiles\lsp-servers\pyls-ms> .\pyls-ms.cmd
^C^CTerminate batch job (Y/N)? y
PS C:\Users\maksim.kim\vimfiles\lsp-servers\pyls-ms>
```

**Comment by habamax** [comment]
This line doesn't work for me:

https://github.com/mattn/vim-lsp-settings/blob/e20ebb1281d145b369fb51948c2d8eb18e49cc76/installer/install-pyls-ms.cmd#L17

If I change it to 

```
%~dp0\Microsoft.Python.LanguageServer.exe %*
```
Then it works again:

![image](https://user-images.githubusercontent.com/234774/73431506-a18ce980-4351-11ea-97c9-43f380e1d993.png)

**Comment by mattn** [comment]
In my environment,

>%~dp0\Microsoft.Python.LanguageServer.exe %*

This does not work.

**Comment by lithammer** [comment]
Shouldn't that be `dotnet exec Microsoft.Python.LanguageServer.dll` (missing the `exec` part).

```diff
-%%~dp0\dotnet.exe Microsoft.Python.LanguageServer.dll %%* ^
+%%~dp0\dotnet.exe exec Microsoft.Python.LanguageServer.dll %%* ^
```

**Comment by habamax** [comment]
> In my environment,
> 
> > %~dp0\Microsoft.Python.LanguageServer.exe %*
> 
> This does not work.

Sorry, I meant the line in that would go into `pyls-ms.cmd` not to install script

**Comment by habamax** [comment]
> 
> 
> Shouldn't that be `dotnet exec Microsoft.Python.LanguageServer.dll` (missing the `exec` part).
> 
> ```diff
> -%%~dp0\dotnet.exe Microsoft.Python.LanguageServer.dll %%* ^
> +%%~dp0\dotnet.exe exec Microsoft.Python.LanguageServer.dll %%* ^
> ```
![image](https://user-images.githubusercontent.com/234774/73432162-36dcad80-4353-11ea-825c-2097174a92ec.png)

**Comment by habamax** [comment]
> 
> 
> Shouldn't that be `dotnet exec Microsoft.Python.LanguageServer.dll` (missing the `exec` part).
> 
> ```diff
> -%%~dp0\dotnet.exe Microsoft.Python.LanguageServer.dll %%* ^
> +%%~dp0\dotnet.exe exec Microsoft.Python.LanguageServer.dll %%* ^
> ```

without exec it works if If I call `pyls-ms.cmd` from powershell but doesn't work for vim-lsp, see log file I have provided earlier.

**Comment by mattn** [comment]
Ah, Could it be that is SxS ?

**Comment by habamax** [comment]
> Ah, Could it be that is SxS ?

What is this?

**Comment by mattn** [comment]
Could you please try below's two `pyls-ms.cmd` both?
```
@echo off
%~dp0\dotnet.exe %~dp0\Microsoft.Python.LanguageServer.dll %* 
```

```
@echo off
cd %~dp0\
%~dp0\dotnet.exe Microsoft.Python.LanguageServer.dll %* 
```

**Comment by mattn** [comment]
Two more.
Could you please try below's two `pyls-ms.cmd` both?
```
@echo off
%~dp0\dotnet.exe %~dp0\Microsoft.Python.LanguageServer.dll
```

```
@echo off
cd %~dp0\
%~dp0\dotnet.exe Microsoft.Python.LanguageServer.dll
```

**Comment by habamax** [comment]
> 
> 
> Could you please try below's two `pyls-ms.cmd` both?
> 
> ```
> @echo off
> %~dp0\dotnet.exe %~dp0\Microsoft.Python.LanguageServer.dll %* 
> ```

This one works!

> 
> ```
> @echo off
> cd %~dp0\
> %~dp0\dotnet.exe Microsoft.Python.LanguageServer.dll %* 
> ```

This one doesn't work.

**Comment by habamax** [comment]
> 
> 
> Two more.
> 
> ```
> @echo off
> %~dp0\dotnet.exe %~dp0\Microsoft.Python.LanguageServer.dll
> ```

Works!

> 
> ```
> @echo off
> cd %~dp0\
> %~dp0\dotnet.exe Microsoft.Python.LanguageServer.dll
> ```

Doesn't work.

**Comment by mattn** [comment]
Okay. Thanks. Fixed in master branch.

**Comment by habamax** [comment]
Thx! it works!
