### ISSUE TITLE
I can get this to work

### ISSUE THREAD

**Issue by cjnucette** [mattn/vim-lsp-settings#135]
When I run `:LspInstallServer typescript-language-server`, it responds with `server not found` (I tried different ones: rls, vim, etc).
If I run `:LspInstallServer` without arguments, then it goes and fetches efm-langserver and installs it.
Am I doing something wrong?
Thanks.

**Comment by mattn** [comment]
Before do the command, please open ts file.

**Comment by cjnucette** [comment]
Yep, never mind. I just found out. Thanks.
