### ISSUE TITLE
What is expected gopls setup?

### ISSUE THREAD

**Issue by habamax** [mattn/vim-lsp-settings#149]
Struggle to make go language server work in my environment (Win10, latest vim/neovim).

1. I have installed `gopls` with `LspInstallServer`
2. Open random `test.go` file with hello world:
```
package main

import "fmt"

func main() {
	fmt.Println("Hello World!)
}
```
3. `LspStatus` shows nothing, No autocompletion, looks like server is not running.
4. Log:
```
08.02.2020 18:51:45:["vim-lsp signs enabled"]
08.02.2020 18:51:45:["vim-lsp highlighting enabled (textprop)"]
08.02.2020 18:51:45:["s:on_text_document_did_open()",1,"txt","C:\\Users\\maksim.kim\\scoop\\apps\\vim-nightly\\current",""]
08.02.2020 18:51:49:["s:on_text_document_did_close()",3]
08.02.2020 18:51:49:["s:on_text_document_did_open()",1,"go","C:\\Users\\maksim.kim\\scoop\\apps\\vim-nightly\\current","file:///C:/Users/maksim.kim/projects/test.go"]
08.02.2020 18:51:53:["s:on_text_document_did_change()",3]
08.02.2020 18:51:53:["s:send_didchange_queue() will be triggered"]
08.02.2020 18:51:57:["s:send_event_queue()"]
08.02.2020 18:52:02:["s:on_text_document_did_close()",3]
```

Probably I miss something crucial?

PS,

After that I have also created root marker (`.git` folder) and `go.mod` file -- still nothing works.

**Comment by mattn** [comment]
What you get with?
```
:echo lsp_settings#exec_path("gopls")
```

**Comment by habamax** [comment]
> :echo lsp_settings#exec_path("gopls")

Nothing.

It is installed with `LspInstallServer` to `~/vimfiles/lsp-servers/gopls/gopls.exe`

relevant vimrc
```
let g:lsp_settings_servers_dir = fnamemodify($MYVIMRC, ":p:h") . "/lsp-servers/"
if !isdirectory(g:lsp_settings_servers_dir) | call mkdir(g:lsp_settings_servers_dir, "p") | endif
```

**Comment by mattn** [comment]
Hmm, I tried same configuration but `:echo lsp_settings#exec_path("gopls")` return path exists.

**Comment by habamax** [comment]
I have several language servers installed and they works too, except this one for go.

**Comment by habamax** [comment]
```
echo globpath('C:\Users\maksim.kim\vimfiles\lsp-servers\gopls', 'gopls.exe')
```
This can't find the executable (debugging now)

**Comment by habamax** [comment]
```
echo globpath('C:\Users\maksim.kim\vimfiles\lsp-servers\pyls-ms', 'pyls-ms.cmd')
```
This works

**Comment by mattn** [comment]
Ah, what is your `&suffixes` ?

**Comment by habamax** [comment]
> 
> 
> Ah, what is your `&suffixes` ?

Yeah just found it!

```
echo globpath('C:\Users\maksim.kim\vimfiles\lsp-servers\gopls', 'gopls.exe', v:true)
```

works!

So `&suffiexes` is `.bak,~,.o,.h,.info,.swp,.obj`
and `&wildignore` is `*.o,*.obj,*.bak,*.exe,*.swp,*.pdf,*.docx,*.xlsx,*.png,*.pyc`

**Comment by habamax** [comment]
Ok, now `echo lsp_settings#exec_path("gopls")` returns path but `LspStatus` still emtpy...

**Comment by habamax** [comment]
Aand it works! If you change all globpaths with `v:true`!

**Comment by mattn** [comment]
Right, now I pushed fixes in master branch.

**Comment by habamax** [comment]
It works! thanks!
