### ISSUE TITLE
gopls fuzzy matching setting

### ISSUE THREAD

**Issue by habamax** [mattn/vim-lsp-settings#150]
Is it possible to setup gopls for fuzzy matching of completion candidates?

https://github.com/golang/go/issues/32754

Looks like for govim it is enabled by default

**Comment by mattn** [comment]
will consider this positively

**Comment by habamax** [comment]
Thank you! Do I have to do anything specific to make it work? Like reinstall lsp-server or smth else?

**Comment by mattn** [comment]
Nothing to do. Currently, fuzzy search is enabled in default on glpls. But maintenar of gopls says:

>We turned them off for the release, but let's keep them on at master so
that we can get more feedback.

So I enabled for that.

https://github.com/golang/tools/commit/87d9f09c5d89af11d60862c48a7869a0a75b3543

**Comment by lithammer** [comment]
> Currently, fuzzy search is enabled in default on glpls.

Is that wanted though? It's extremely awkward when used together with `omnifunc`. But maybe I'm in the minority when it comes to not using some kind of auto-complete plugin 🤷‍♂

**Comment by mattn** [comment]
This is not related on auto-complete plugins. This should works with omnifunc.
