### ISSUE TITLE
[Request] Adding Julia (Lanuage Server)

### ISSUE THREAD

**Issue by kozo2** [mattn/vim-lsp-settings#151]
The [Julia language](https://julialang.org/) also has a Language Server.

https://github.com/julia-vscode/LanguageServer.jl

Can I ask you the additional support (for Julia)?

**Comment by mattn** [comment]
It is possible to add Julia Language Server to the vim-lsp-settings entry. However, the current Julia Language Server has broken dependencies on CSTParser and SymbolServer. I'm already confirm Julia Language Server works with vim-lsp-settings.

```
add LanguageServer.jl#master
```
https://twitter.com/mattn_jp/status/1223420691095048192

**Comment by kozo2** [comment]
Thank you for the information (Sorry, I did not check it.)
I'll keep watching LanguageServer.jl.
I will request again when LanguageServer.jl improves.
I close this once.

**Comment by mattn** [comment]
I keep this open until julia branch will be merged. Thanks.

https://github.com/mattn/vim-lsp-settings/tree/julia
