### ISSUE TITLE
Yaml throws 'dynamicRegistration' of undefined

### ISSUE THREAD

**Issue by husainaloos** [mattn/vim-lsp-settings#155]
Two issues here:

- yaml language server throws `Cannot read property 'dynamicRegistration' of undefined` error. Maybe something similar to this: https://github.com/sublimelsp/LSP/issues/649
- yaml language server cannot be uninstalled. I get `invalid server name`

**Comment by mattn** [comment]
I don't reproduce this but this patch fix your issue?

```diff
diff --git a/settings/yaml-language-server.vim b/settings/yaml-language-server.vim
index e16abef..08f766d 100644
--- a/settings/yaml-language-server.vim
+++ b/settings/yaml-language-server.vim
@@ -8,6 +8,9 @@ augroup vimlsp_settings_yaml_language_server
       \ 'whitelist': lsp_settings#get('yaml-language-server', 'whitelist', ['yaml']),
       \ 'blacklist': lsp_settings#get('yaml-language-server', 'blacklist', []),
       \ 'config': lsp_settings#get('yaml-language-server', 'config', {}),
-      \ 'workspace_config': lsp_settings#get('yaml-language-server', 'workspace_config', {name, key->{'json': {'format': {'enable': v:true}, 'schemas': json_decode(join(readfile(expand('<sfile>:h:h') . '/data/catalog.json'), "\n"))['schemas']}}}),
+      \ 'workspace_config': lsp_settings#get('yaml-language-server', 'workspace_config', {name, key->{
+      \   'symbol': {'symbolKind': {'valueSet': range(1, 26)}},
+      \   'json': {'format': {'enable': v:true}, 'schemas': json_decode(join(readfile(expand('<sfile>:h:h') . '/data/catalog.json'), "\n"))['schemas']},
+      \ }}),
       \ }
 augroup END
```

**Comment by mattn** [comment]
Probably, you can install with:

1. Open yaml file
2. `:LspInstallServer`

**Comment by husainaloos** [comment]
That unfortunately didn't solve it :/

Still getting the same error. However, if you are not able to reproduce it, let me look into how to reproduce it if I can so that I know the root cause.

**Comment by mattn** [comment]
Could you please upgrade yaml-language-server to 0.6.0 ?

**Comment by husainaloos** [comment]
> Could you please upgrade yaml-language-server to 0.6.0 ?

Thank you. This helped me find the issue.

It appears that I already have yaml-language-server installed on my machine with outdated version. The solution was to remove that one and have `vim-lsp-settings` handle the downloading.

Doing so fixed the issue.
