### ISSUE TITLE
[RFC] Change location of default servers directory

### ISSUE THREAD

**Issue by mattn** [mattn/vim-lsp-settings#165]
Currently, vim-lsp-settings install servers into servers sub-directory. This is useful for me to check behavior of installers. But some users want to change the location. As you know, `lsp_settings_servers_dir` can use to change the location of servers directory.
Now I'm going to change the default location to other. So I hope to hear anyone's opinion. My suggestion is:

On UNIX, the location is `$HOME/.config/lsp-servers`, On Windows, `%APPDATA%\lsp-servers`. What do you think?

**Comment by johejo** [comment]
Most lsp servers are not tightly coupled with vim-lsp-settings, so I think it's not bad `lsp-servers`.
However, I think some people don't like the difference between the name of the tool and the name of the directory.

And some installer creates entrypoint script or symlink.
Those are created for vim-lsp-settings but also available from other editors.
But someone might think that the name should include `vim-lsp-settings`, as it is including not only the LSP servers but also including wrapper scrips or symlinks.

**Comment by tyru** [comment]
👍 to `vim-lsp-settings`.

**Comment by mattn** [comment]
@tyru so you don't mind that the servers is located at there?

```
/home/tyru/.config/vim-lsp-settings
  + eslint-language-server
  + gopls
```

Or servers directory is required?
```
/home/tyru/.config/vim-lsp-settings
  + servers
    + eslint-language-server
    + gopls
```

**Comment by thinca** [comment]
I 👍 for second one. (`servers` is required)

**Comment by thinca** [comment]
Another opinion:
Installed servers are data, not configs.  So we should `$XDG_DATA_HOME`(= `$HOME/.local/share`) use instead of `$XDG_CONFIG_HOME`(= `$HOME/.config`).

ref: https://specifications.freedesktop.org/basedir-spec/latest/ar01s03.html

(I do not disagree with `$HOME/.config`)
