### ISSUE TITLE
Add 'semantic_highlight' to the list of keys which can be overridden with g:lsp_settings

### ISSUE THREAD

**Issue by jmdevin** [mattn/vim-lsp-settings#177]
## Information

`prabirshrestha/vim-lsp` allows users to enable lsp-powered semantic highlighting.

From `:h vim-lsp-semantic`:

```vimscript
Suppose we want to highlight classes using |Identifier| and functions using
|Label|. The language server registration for Eclipse LS will look like: >
    autocmd User lsp_setup call lsp#register_server({
        \ 'name': 'eclipse.jdt.ls',
        \ 'cmd': {server_info->[...]},
        \ 'whitelist': ['java'],
        \ 'semantic_highlight': {
        \       'entity.name.type.class.java': 'Identifier',
        \       'entity.name.function.java': 'Label'
        \ }
        \ })
```

It is not currently possible for users to enable this with language servers configured by `mattn/vim-lsp-settings`, as there is no overrideable key in `g:lsp_settings`.

## Proposal

Add the ability for users to enable lsp-powered semantic highlighting through `g:lsp_settings`.

#### Example

```vimscript
let g:lsp_settings = {
    \ 'example_lsp': {
    \     'semantic_highlight': {
    \         'foo.bar.bizz': 'Function',
    \         'buzz.thing.bat': 'Identifier',
    \     }
    \ }
\ }

**Comment by jmdevin** [comment]
Talk about that response time. Thanks

**Comment by mattn** [comment]
FYI, you can specify semantic_highlight for project local with `:LspSettingsEditLocal`. Thanks.
