### ISSUE TITLE
Pyls/Python do not suggest in Windows

### ISSUE THREAD

**Issue by tsuyoshicho** [mattn/vim-lsp-settings#18]
https://github.com/mattn/vim-lsp-settings/blob/73153e820f1748e23aaa2e1e6b8717aefb44ba9e/settings.json#L42-L48

Currently pyls requires "python3" command (check in https://github.com/mattn/vim-lsp-settings/blob/73153e820f1748e23aaa2e1e6b8717aefb44ba9e/plugin/lsp_settings.vim#L46-L51 )

But, windows python3 installed in python.exe, suggestion failed.

**Comment by mattn** [comment]
Could you please send me pull-request?

**Comment by tsuyoshicho** [comment]
OK, I think resolving method...
