### ISSUE TITLE
Error when running :LspInstallServer

### ISSUE THREAD

**Issue by hnakamur** [mattn/vim-lsp-settings#19]
I got the following error when I tried `LspInstallServer` in a fresh environment with https://github.com/mattn/vim-lsp-settings/commit/d7353a2bf491e1e6c7d4f7bf1e54e624fb7955e1

```
/home/hnakamur/.vim/plugged/vim-lsp-settings/settings/gopls.vim
Error detected while processing /home/hnakamur/.vim/plugged/vim-lsp-settings/settings/gopls.vim:
line     12:
E492: Not an editor command:   LspRegisterServer { ...(snip)...
```
![image](https://user-images.githubusercontent.com/19299/71431616-6aa23300-2716-11ea-96a8-a613493970b1.png)

`~/.vimrc`
```
call plug#begin('~/.vim/plugged')
Plug 'prabirshrestha/async.vim'
Plug 'prabirshrestha/vim-lsp'
Plug 'mattn/vim-lsp-settings'
call plug#end()
```

**Comment by hnakamur** [comment]
Thanks for commit https://github.com/mattn/vim-lsp-settings/commit/0f97d334955d9568e6cc626458af113263862765

I refreshed my `~/.vim` with the following script.
```
#!/bin/sh
rm -rf ~/.vim ~/.viminfo
curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
            https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
vim +PlugInstall +q +q
```

And I run
`vim -V9vim.log main.go`
and noticed that `If you want to enable Language Server, please do :LspInstallServer` is not printed anymore. Is this intended?
Also when I run `:LspInstallServer`, I got the following error.
`E492: Not an editor command: LspInstallServer`

**Comment by mattn** [comment]
Could you please try remove /path/to/vim-lsp-settings/servers/gopls and try it again?

**Comment by mattn** [comment]
I added one more fix to recognize command paths.

**Comment by hnakamur** [comment]
Thanks for another commit!
However the error situation is still the same.
I'm using Vim version 8.0.1453 on Ubuntu 18.04 LTS.

`~/.vimrc`
```
call plug#begin('~/.vim/plugged')
Plug 'prabirshrestha/async.vim'
Plug 'prabirshrestha/vim-lsp'
Plug 'mattn/vim-lsp-settings'
call plug#end()
```

```
rm -rf ~/.vim ~/.viminfo
curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
            https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
vim +PlugInstall +q +q
```

```
# (cd ~/.vim/plugged/vim-lsp-settings/; git rev-parse HEAD)
a7c843b879f937007c9c20751e8258e31c050cad
```

`vim -V9vim.log main.go`

*  `If you want to enable Language Server, please do :LspInstallServer` is not printed
* `E492: Not an editor command: LspInstallServer` when I run `:LspInstallServer`

**Comment by hnakamur** [comment]
According to `vim.log`, `vim-lsp-settings/plugin/lsp_settings.vim` seems to be sourced correctly.
```
sourcing "/root/.vim/plugged/vim-lsp-settings/plugin/lsp_settings.vim"
finished sourcing /root/.vim/plugged/vim-lsp-settings/plugin/lsp_settings.vim
```

**Comment by hnakamur** [comment]
I'm sorry, it was my mistake.
With commit a7c843b87, it works as expected.

When I run `vim main.go`, `If you want to enable Language Server, please do :LspInstallServer` is printed.
When I run `:LspInstallServer`, it installes `gopls` to `~/.vim/plugged/vim-lsp-settings/servers/gopls/gopls` successfully.

I'm closing this issue now.
Thanks for your support!

**Comment by mattn** [comment]
Thanks!
