### ISSUE TITLE
[gopls] go: cannot use path@version syntax in GOPATH mode

### ISSUE THREAD

**Issue by habamax** [mattn/vim-lsp-settings#191]
vim: latest nightly (8.2.360)
OS: win10

Tried to reinstall `gopls` using new default server location and get this error:

```
go: cannot use path@version syntax in GOPATH mode
```

![image](https://user-images.githubusercontent.com/234774/76144122-4952b100-608e-11ea-9769-c66915d663cc.png)

I've got NULL filename where gopls server should be:
![image](https://user-images.githubusercontent.com/234774/76144128-65565280-608e-11ea-9786-a4fad647614b.png)

And the content is:

![image](https://user-images.githubusercontent.com/234774/76144136-73a46e80-608e-11ea-9097-9f3ee36e88c8.png)

**Comment by mattn** [comment]
Do you set `GO111MODULE` ?

**Comment by habamax** [comment]
No, didn't touch any go variables

**Comment by mattn** [comment]
What go version do you use?

**Comment by habamax** [comment]
1.14

**Comment by mattn** [comment]
Do you set GOPATH? Where is current directory?

**Comment by habamax** [comment]
> Do you set GOPATH? Where is current directory?

Not sure if I explicitly set it up. Will be back at my laptop in an hour and let u know. Thx.

**Comment by habamax** [comment]
> Do you set GOPATH? Where is current directory?

`echo $GOPATH` is empty.

What kind of current directory you do mean?

Go related, I have only `GOROOT`:

![image](https://user-images.githubusercontent.com/234774/76146884-07ceff80-60a8-11ea-919e-0474c709225a.png)

**Comment by habamax** [comment]
Is this somehow related?

https://stackoverflow.com/questions/54415733/getting-gopath-error-go-cannot-use-pathversion-syntax-in-gopath-mode-in-ubun

**Comment by habamax** [comment]
If I go into my test project and issue:

`go get -v -u golang.org/x/tools/gopls@latest` it starts downloading gopls

**Comment by habamax** [comment]
Not sure if it helps, test go project I open in vim and try LspInstallServer:

[mytest.zip](https://github.com/mattn/vim-lsp-settings/files/4302128/mytest.zip)

**Comment by habamax** [comment]
Ok, I have created GO111MODULE environment variable with value `on` and it works now. (It worked without it for me last time I tried)

![image](https://user-images.githubusercontent.com/234774/76147231-369aa500-60ab-11ea-98e0-a4b8d150017d.png)

**Comment by habamax** [comment]
Thx!
