### ISSUE TITLE
Eclipse (Java) LSP is 

### ISSUE THREAD

**Issue by husainaloos** [mattn/vim-lsp-settings#197]
I updated my plugins today, and installed the LSP via `LspInstallServer`. I ran into this issue:

```
Error detected while processing function <SNR>79_register_command[5]..lsp#register_command[1]..lsp#ui#vim#execute_command#_register:
line    2:
E605: Exception not caught: lsp#ui#vim#execute_command#_register_command: java.apply.workspaceEdit already registered.
Press ENTER or type command to continue
```

Not sure what's going on.

**Comment by jack-michaud** [comment]
Just came across this today, a recent change in the `vim-lsp` interface caused this error (see https://github.com/prabirshrestha/vim-lsp/pull/735)

The temp fix is to pin the vim-lsp server to the commit before that merge... I have this in my vimrc.

```
Plug 'prabirshrestha/vim-lsp', { 'commit': '4630823' }
```

**Comment by jack-michaud** [comment]
Thank you @mattn, that was super speedy! Just confirmed your fix works.

**Comment by mattn** [comment]
Thanks you too.
