### ISSUE TITLE
Link to prabirshrestha/vim-lsp may be helpful in README.md

### ISSUE THREAD

**Issue by ichihara-3** [mattn/vim-lsp-settings#20]
Hi. 
I read the article in Qiita: https://qiita.com/mattn/items/e62b9f16bc487a271a7f and just started to use this plugin.

Thank you for the plugin! It's completely useful to me.

When I installed vim-lsp-settings without installing vim-lsp, of course, running LspInstallServer failed.

```
User Autocommands for "lsp_setup" の処理中にエラーが検出されました:
E117: 未知の関数です: lsp#register_server
E117: 未知の関数です: lsp#register_server
```

I think some instructions for installing vim-lsp in README.md may be helpful.

**Comment by mattn** [comment]
Thanks your pointing this. Will do in later.
