### ISSUE TITLE
How to configure flake8

### ISSUE THREAD

**Issue by logston** [mattn/vim-lsp-settings#200]
I'm getting stuck on how to configure the `lsp_settings` variable such that flake8 is the default linter rather than pycodestyle (which is set by vim-lsp).

In my ~/.vimrc file I have...

```
let g:lsp_settings = {                                                                                                                                                                                    
\  'python': {
\    'config': { 'configurationSources': ["flake8"] }
\  },  
\}
```

But this and several other variations are not working. Any help is greatly appreciated.

**Comment by johejo** [comment]
Hi, it seems that pyls config need to be set.
https://github.com/palantir/python-language-server/blob/develop/README.rst#configuration

**Comment by logston** [comment]
Thank you @johejo. However, I'm new to this and I don't know where that file is. 

I've read the line: 

> To enable pydocstyle for linting docstrings add the following setting in your LSP configuration: ` "pyls.plugins.pydocstyle.enabled": true `

But I don't know where to put that.

**Comment by johejo** [comment]
Try, this.

```
let g:lsp_settings = {
\   'pyls': {'config': {'pyls.configurationSources': ['flake8']}},
\}
```

The `g:lsp_settings` overrides `settings/{LANGUAGE_SERVER_NAME}.vim`.
https://github.com/mattn/vim-lsp-settings/blob/f361e8e88cc6c130885c3ae24991415cfcc649d1/settings/pyls.vim#L1-L14

**Comment by logston** [comment]
Thank you @johejo, but for some reason that does not seem to work. From what I can gather, the dict/map `{'config': {'pyls.configurationSources': ['flake8']}}` is being passed to `lsp#register_server` as `server_info` by the vim-lsp-settings repo:

https://github.com/mattn/vim-lsp-settings/blob/f361e8e88cc6c130885c3ae24991415cfcc649d1/autoload/lsp_settings.vim#L294

https://github.com/prabirshrestha/vim-lsp/blob/46308234a2691824f2f3ad1fa8bc0086d4a3d4cf/autoload/lsp.vim#L155

I even added a `name` key given the code in vim-lsp:

```
let g:lsp_settings = {   
\   'pyls': {'config': {'name': 'pyls', 'pyls.configurationSources': ['flake8']}},                                                                                                                        
\} 
```

But still no luck. 

If I wanted to debug this issue, could I clone this repo and the `vim-lsp` repo into my `~/.vim/plugged/` directory and add debugging statements? Is there such a thing in vimscript? Is there a gdb tool for vim? I know this might not be the best venue for this question but I'm hoping you can guide me to the right tools and techniques so that I don't spend time searching on Google for best practices if not necessary.

**Comment by lithammer** [comment]
I think what you're looking for is this (it's a bit confusing with that dot notation used here and there):

```vim
let g:lsp_settings = {   
\   'pyls': {'config': {'pyls': {'configurationSources': ['flake8']}}},                                                                                                                        
\} 
```

**Comment by logston** [comment]
This is returned from `lsp_settings#get` in `vim-lsp-settings`:

```
{'pyls': {'configurationSources': ['flake8']}}
```

This is passed to `lsp#register_server` in `vim-lsp`:

```
{'cmd': function('<lambda>1'), 'initialization_options': v:null, 'root_uri': function('<lambda>2'), 'name': 'pyls', 'blacklist': [], 'whitelist': ['python'], 'semantic_highlight': {}, 'workspace_config':
{}, 'config': {'pyls': {'configurationSources': ['flake8']}}}
```

Unfortunately, this is still not working. Do either of you know what function in `vim-lsp` calls out to pyls to configure it to use `flake8`? Many thanks.

**Comment by lithammer** [comment]
Try `workspace_config` instead of `config`.

```vim
let g:lsp_settings = {
      \ 'pyls': {'workspace_config': {'pyls': {'configurationSources': ['flake8']}}}
      \} 
```

**Comment by logston** [comment]
Hey!!! That was it! Many thanks @lithammer! I'll read up on `workspace_config` but can you briefly describe what was going wrong?

**Comment by lithammer** [comment]
I don't know for sure. But I think `config` is just configuration for the vim-lsp plugin itself as you can see in its [documentation](https://github.com/prabirshrestha/vim-lsp/blob/4d8cd302bb278ad5047a3977189222b5dcf19297/doc/vim-lsp.txt#L775-L832). While `workspace_config` is the actual LSP configuration to the server.

**Comment by logston** [comment]
Got it. Thank you very much @lithammer.

**Comment by testfailagain** [comment]
Hello, I have the same problem but when I tried to put that code in the init.lua file:

```
Error detected while processing ~/.config/neovim/init.lua:
E5112: Error while creating lua chunk: ~/.config/neovim/init.lua:22: '=' expected near 'g'
Press ENTER or type command to continue
```

And I don't know what to do
