### ISSUE TITLE
Wants to install generic language server in Nim

### ISSUE THREAD

**Issue by xigoi** [mattn/vim-lsp-settings#222]
The table in README says that `nimls` is supported as the language server for Nim, but when I open a Nim file and do `:LspInstallServer`, it wants to install the generic `efm-langserver`.
![image](https://user-images.githubusercontent.com/16985175/80256068-a53cbd80-866d-11ea-9f94-3153f2debdaf.png)

**Comment by xigoi** [comment]
If I do `:LspInstallServer nimls`, it says "Server not found".

**Comment by mattn** [comment]
Do you install syntax plugins for nim?

**Comment by mattn** [comment]
Ah, sorry. I was confused.

**Comment by mattn** [comment]
Do you know how to specify install location of nimls?

**Comment by xigoi** [comment]
Sorry, what do you mean by that?

**Comment by mattn** [comment]
vim-lsp-settings install language server into `~/.local/share/vim-lsp-settings/servers/nimlsp/`. So I want to know the way to specify the path for installation.
