### ISSUE TITLE
Help needed: rust-analyzer not start after installed

### ISSUE THREAD

**Issue by phuna** [mattn/vim-lsp-settings#228]
After installing rust-analyzer using `:LspInstallServer`, restart neovim, check `:LspStatus` I only see `rls : exited`.
I'm using neovim & vim-plug and here's plugins I installed for vim-lsp:
```
Plug 'prabirshrestha/async.vim'
Plug 'prabirshrestha/vim-lsp'
Plug 'prabirshrestha/asyncomplete.vim'
Plug 'prabirshrestha/asyncomplete-lsp.vim'
Plug 'mattn/vim-lsp-settings'
```

**Comment by prabirshrestha** [comment]
Can you provide OS and neovim version? Also did it work in vim?

**Comment by phuna** [comment]
I'm using macOS 10.15.4, neovim 0.4.3 installed using homebrew. I haven't tried vim yet, if you need that I'll give it a try after work.

**Comment by phuna** [comment]
I removed `~/.vim` then reinstalled all the plugins and now it works. Weird.
Thanks for your time.
