### ISSUE TITLE
Not all language servers will install?

### ISSUE THREAD

**Issue by ludwj61** [mattn/vim-lsp-settings#241]
I can't seem to get some of the language servers to work. For example, the python server was prompted to install and worked fine, and the rust integration worked perfectly as well when I followed instructions. However, when I open a Lua file, for example, I am not prompted to install a Server and when I try I get "no server found." 

Sorry if the answer is obvious but I am stumped as the readme says Lua uses a local install like Python.

**Comment by mattn** [comment]
To install Language Server for Lua, you need to install Java.

https://github.com/mattn/vim-lsp-settings/blob/a84a149e256a00c4bbd048c96d9f31e7e181478c/settings.json#L398

**Comment by ludwj61** [comment]
Thanks!
