### ISSUE TITLE
Installation scripts don't use g:lsp_settings_servers_dir

### ISSUE THREAD

**Issue by SCOTT-HAMILTON** [mattn/vim-lsp-settings#253]
The installation scripts don't use the lsp_settings_servers_dir variable. 
Since the installer scripts are located in store path instead of home folder in NixOS, I get this error : 
`mkdir: cannot create directory ‘../servers/pyls’: Read-only file system                                                                                                                         
Error: [Errno 30] Read-only file system: '/nix/store/ijzkx3434dnh17bqw2x6jzxhbbq6lqgg-vimplugin-vim-lsp-settings-0.0.1/share/vim-plugins/vim-lsp-settings/installer/venv'`

**Comment by mattn** [comment]
This should be fixed in latest behavior.
