### ISSUE TITLE
Is there any way to support LanguageClient-neovim and coc.nvim  ?

### ISSUE THREAD

**Issue by leoatchina** [mattn/vim-lsp-settings#26]
I have read the script and found it installed some local lsp servers under the `servers` directroy.

So, is there any way LCN or COC can make use of them ?

**Comment by mattn** [comment]
I'm not a user of LCN or COC. So I don't have a plan to add code for them. However you can use shell/batch files in install directory. Please note that put LICENSE of vim-lsp-settings on your project if you want to copy the files.
