### ISSUE TITLE
css-languageserver should be whitelisted for less and sass too

### ISSUE THREAD

**Issue by prabirshrestha** [mattn/vim-lsp-settings#27]
just updating the whitelist doesn't seem to work unlike typescript. is there some where else that I need to update?

```
  \ 'whitelist': lsp_settings#get('css-languageserver', 'whitelist', ['css', 'less', 'sass']),
```

**Comment by mattn** [comment]
Yes, pls send me pull-request.

**Comment by prabirshrestha** [comment]
Just that setting didn't work for me. Is there any other files I need to modify?

**Comment by mattn** [comment]
Could you please try last change?

**Comment by prabirshrestha** [comment]
Doesn't work.

![image](https://user-images.githubusercontent.com/287744/71454717-e0be8e00-2746-11ea-8ca7-27b78e24ceb2.png)

I don't have the language server installed so it doesn't even show `Please install using LspInstallServer` message.

**Comment by mattn** [comment]
Now LspInstallServer always defined. Please try the command.

**Comment by prabirshrestha** [comment]
It doesn't seem defined yet.

**Comment by mattn** [comment]
Hmm, on my environment, css-languageserver is runninng.

**Comment by prabirshrestha** [comment]
Are you trying on a .less file?

**Comment by mattn** [comment]
Ah, we should add less and sass into settings.json.

**Comment by mattn** [comment]
Added

**Comment by prabirshrestha** [comment]
It works now. That was exactly what I was missing.

Thanks for the fix.
