### ISSUE TITLE
'npm_install' is not recognized as an internal or external command when using with vim-rooter

### ISSUE THREAD

**Issue by prabirshrestha** [mattn/vim-lsp-settings#28]
I'm getting the following error when I try to install a language server that uses npm

```
'npm_install' is not recognized as an internal or external command,
operable program or batch file.
```

Seems like when using this plugin https://github.com/airblade/vim-rooter, the working directory is the same as vim instead so `cd %~dp0` doesn't work as expected and cannot find `npm_install` command.

**Comment by mattn** [comment]
I tried installation of css-languageserver with vim-rooter but I could not reproduce.

**Comment by prabirshrestha** [comment]
hmm. wondering if it is some other plugin or my vimrc settings.

Do you also have shellslash enabled?

Here is my full vimrc. I will try with minimal vimrc later.

https://gist.github.com/prabirshrestha/279d8b179d9353fe8694#file-vimrc

**Comment by mattn** [comment]
I don't use shellslash (since I don't like it)

Hmm, As far as I know, `%~dp0` mean the directory of the batch file `%f`.

![image](https://user-images.githubusercontent.com/10111/71455197-57a36780-27d7-11ea-91f1-fcdf41892bfb.png)

**Comment by prabirshrestha** [comment]
```
call %~dp0npm_install css-languageserver %~dp0..\server\vscode-css-languageserver-bin
```

This seems to partially work but it is install in the wrong folder.

**Comment by mattn** [comment]
Do you use symbolic link?

**Comment by mattn** [comment]
How `cd /d %~dp0` works?

**Comment by prabirshrestha** [comment]
`cd /d %~dp0` works.

I don't use symoblic links for my vim configs. But I do use it for npm and node since I use [scoop](https://scoop.sh/)  as package installer for windows and it has heavy use of symbolic link.

I think my issue was that I was editing a css file from `d:` and `cd` without `/d` didn't change the drive. Now it work.

**Comment by mattn** [comment]
Fixed all `.cmd` files.

**Comment by prabirshrestha** [comment]
That was fast! Works now. Thanks for digging in.
