### ISSUE TITLE
unzip unrecognized on windows

### ISSUE THREAD

**Issue by prabirshrestha** [mattn/vim-lsp-settings#29]
Windows doesn't ship with unzip but it ships with tar.exe - https://docs.microsoft.com/en-us/virtualization/community/team-blog/2017/20171219-tar-and-curl-come-to-windows

Unfortunately omnisharp doesn't seem to have tar.

Might be good to have check for `unzip` and if it doesn't exist using powershell to extract.

https://github.com/prabirshrestha/vim-lsp/blob/e4422f660b492aa8263eb46a38ed95e456f78112/.github/workflows/windows_vim.yml#L42

Powershell might requires signed scripts so it should still perfer unzip.exe over powershell unzip.

**Comment by prabirshrestha** [comment]
Actually might be able to do it using vbscript. 

https://superuser.com/a/1314429/79099

**Comment by mattn** [comment]
It seems that Microsoft does not recomend this way.

**Comment by prabirshrestha** [comment]
What about using these `unzip` > `7z`> `powershell`.

Might be good to have a `extract_archive.cmd` so other scripts can easily use it?

**Comment by prabirshrestha** [comment]
Actually what if you just upload `unzip.exe` win32 bit to the release and download it from here for windows if it doesn't exist? That would make it easy.

Downloading wouldn't be a problem because curl already exists in windows.

**Comment by mattn** [comment]
I added run_unzip.cmd that download unzip.exe on release page if it does not exists on the system.

**Comment by prabirshrestha** [comment]
Works. This is great. It will make it lot easier for new users to install in windows without telling them where to find unzip.exe. 

Also you should add unzip.exe to gitignore.

Given that vim also knowns how to read unzip might be it should support unzip function :)

**Comment by prabirshrestha** [comment]
Thanks for the improvements.
