### ISSUE TITLE
:LspInstallServer in Neovim gives an error

### ISSUE THREAD

**Issue by johejo** [mattn/vim-lsp-settings#31]
Occurs in Neovim.

```
:LspInstallServer
Error detected while processing function <SNR>47_vimlsp_install_server:
line    3:
E117: Unknown function: term_getjob
E15: Invalid expression: term_getjob(bufnr('%'))
```

https://github.com/mattn/vim-lsp-settings/blob/b13a1e4664a1ff4c69fbe69f8ec59d30d7a228da/plugin/lsp_settings.vim#L100

**Comment by johejo** [comment]
@mattn Could you add label such as "help wanted", "PR welcome"?

**Comment by hrsh7th** [comment]
I think, We should use `termopen` function instead of `:terminal` command if nvim.

**Comment by nabezokodaikon** [comment]
Hmm. Seems difficult.
https://github.com/neovim/neovim/blob/e922576bdd6abd6736417343121120b289079565/runtime/pack/dist/opt/termdebug/plugin/termdebug.vim#L42

**Comment by prabirshrestha** [comment]
I had ported vim-fz to support neovim and vim8. Can someone try something similar to this? https://github.com/mattn/vim-fz/pull/5

**Comment by sakuraiyuta** [comment]
I wrote dirty-hack:

```diff
diff --git a/plugin/lsp_settings.vim b/plugin/lsp_settings.vim
index 1081bf5..c1bd45a 100644
--- a/plugin/lsp_settings.vim
+++ b/plugin/lsp_settings.vim
@@ -1,3 +1,5 @@
+let s:is_nvim = has('nvim')
+
 if exists('g:loaded_lsp_settings')
   finish
 endif
@@ -96,6 +98,12 @@ function! s:vimlsp_install_server_post(command, job, code) abort
   endif
 endfunction

+if s:is_nvim
+  function! s:vimlsp_install_server_post_nvim(command, job, code, eventtype) abort
+    return s:vimlsp_install_server_post(a:command, a:job, a:code)
+  endfunction
+endif
+
 function! s:vimlsp_install_server() abort
   let l:entry = s:vimlsp_installer()
   let l:servers_dir = get(g:, 'lsp_settings_servers_dir', s:servers_dir)
@@ -104,11 +112,17 @@ function! s:vimlsp_install_server() abort
     call delete(l:server_install_dir, 'rf')
   endif
   call mkdir(l:server_install_dir, 'p')
+
+  if s:is_nvim
+    let l:job = jobstart(l:entry[1], {'cwd': l:server_install_dir, 'on_exit': function('s:vimlsp_install_server_post_nvim', [l:entry[0]])})
+  else
     let l:bufnr = term_start(l:entry[1], {'cwd': l:server_install_dir})
     let l:job = term_getjob(l:bufnr)
     if l:job != v:null
       call job_setoptions(l:job, {'exit_cb': function('s:vimlsp_install_server_post', [l:entry[0]])})
     endif
+  endif
+
 endfunction

 function! s:vimlsp_settings_suggest() abort
```

I'm unfamilier with vim script, and don't know about normal behavior of `:LspInstallServer`.
It maybe makes so curious problems.

See also:
https://github.com/neovim/neovim/pull/8364

**Comment by prabirshrestha** [comment]
I sent a PR and verified it `vim-langauge-server` can install on mac in neovim as well as start. Please give https://github.com/mattn/vim-lsp-settings/pull/56 a try.

**Comment by sakuraiyuta** [comment]
I Also checked #56 on WSL(Ubuntu), seems good to me.

**Comment by leoatchina** [comment]
I also tested #56  on macOS,   with filetype `c`, `vim`, `php`, `bash`, `java`, everything works well.
