### ISSUE TITLE
ConTeXt language server (digestif)

### ISSUE THREAD

**Issue by alvitg** [mattn/vim-lsp-settings#321]
Dear author!

Digestif language server [https://github.com/astoff/digestif](url) which is supported for LaTeX and PlainTeX can be used for ConTeXt [https://wiki.contextgarden.net/Main_Page](url) also. Is it possible to enable ConTeXt support (context filetype) in vim-lsp-settings?

**Comment by mattn** [comment]
What the filetype is for ConTeXt on Vim?

**Comment by alvitg** [comment]
Thank you for the reply.

File extension is the same as for LaTeX - .tex, filetype detected by Vim - 'context'.

By the way, it makes sense to implement ConTeXt support not only for digestif, but for Texlab [https://texlab.netlify.app/](url) server too.

For me adding the following lines:

```
" context
au User lsp_setup call lsp#register_server({
    \ 'name': 'digestifc',
    \ 'cmd': {server_info->['digestif']},
    \ 'allowlist': ['context'],
    \ })
au User lsp_setup call lsp#register_server({
    \ 'name': 'texlabc',
    \ 'cmd': {server_info->['texlab']},
    \ 'allowlist': ['context'],
    \ })
let g:lsp_settings_filetype_context = ['digestifc', 'texlabc']
```

to vimrc tended to apperance of hovers (digestif) and command completions (texlab) while editing.

**Comment by mattn** [comment]
Thanks your explaining. Hmm, the name `context` seems to be too generic name. Please take me a while for my thinking.

**Comment by mattn** [comment]
How about to add new variable like `lsp_settings_ftmap` ?
```
let g:lsp_settings_ftmap = {'context': 'tex'}
```

**Comment by alvitg** [comment]
> How about to add new variable like `lsp_settings_ftmap` ?
> 
> ```
> let g:lsp_settings_ftmap = {'context': 'tex'}
> ```

Interesting idea. It would be a user's way to map language server 'known' to the system to 'new' filetype, wouldn't it? It could be promising in respect of LaTeX, because texlab and digestif support also BiBTeX files. Maybe it would be useful for other language servers.

Or maybe it will be useful to separate the configuration into two layers: 'layer' of known language servers and 'layer' of association of those servers with particular filetypes in the above style.

But please remember, I am not a programmer, so my opinion cannot be particularly valuable.

**Comment by mattn** [comment]
Ah, I didn't know vim include context.vim https://github.com/vim/vim/blob/master/runtime/ftplugin/context.vim

So, it should add context in settings.json.

**Comment by alvitg** [comment]
Sorry, context filetype is not still treated properly: you have forgotten to modify allowlists in digestif.vim and texlab.vim settings. 
```viml
'allowlist': lsp_settings#get('digestif', 'allowlist', ['plaintex', 'tex']), 
->
'allowlist': lsp_settings#get('digestif', 'allowlist', ['plaintex', 'tex', 'context']),
```
