### ISSUE TITLE
Set sumneko-lua globals and library for nvim lua development

### ISSUE THREAD

**Issue by rafi** [mattn/vim-lsp-settings#336]
I'm trying to setup my nvim environment for lua development with the `sumneko-lua-language-server`, following this "working example": https://github.com/sumneko/lua-language-server/wiki/Setting-without-VSCode#working-example

I enabled vim-lsp's `g:lsp_log_file` and tried different ways, but can't seem to get it working:
```json
{
	"sumneko-lua-language-server": {
		"workspace_config": {
			"Lua": {
				"library": {
					"/usr/local/opt/neovim/share/nvim/runtime/lua": true,
					"/usr/local/opt/neovim/share/nvim/runtime/lua/vim/lsp": true
				},
				"diagnostics": {
					"enable": true,
					"globals": "vim",
					"disable": [ "lowercase-global" ]
				}
			}
		}
	}
}
```

**Comment by hrsh7th** [comment]
I think `"globals": "vim"` should be `"globals": ["vim"]`.

**Comment by rafi** [comment]
I discovered the root cause is that my local settings aren't loaded correctly, and once moved to `g:lsp_settings`, everything seems to work as expected.
Thanks @hrsh7th, I've already tried that, but [this](https://github.com/mattn/vim-lsp-settings/blob/master/settings/sumneko-lua-language-server.vim#L19) confused me.

**Comment by razorbear3** [comment]
@rafi How exactly did you get this working? I've tried about everything and cannot seem to get it. Could you share your solution for g:lsp_settings?

**Comment by razorbear3** [comment]
Finally, got it working, here is what worked for me:

`let g:lsp_settings = {
    \  "sumneko-lua-language-server": {
    \       "workspace_config": {
    \           "Lua": {
    \               "diagnostics": {
    \                   "globals": ["vim", "it", "describe", "before_each", "after_each"],
    \                   "disable": ["lowercase-global", "undefined-global", "unused-local", "unused-vararg", "trailing-space"]
    \               }
    \           }
    \       }
    \   }
    \}
`
