### ISSUE TITLE
Add godot (a tcp server)

### ISSUE THREAD

**Issue by idbrii** [mattn/vim-lsp-settings#338]
I figured out how to use TCP using netcat as a proxy.

Here's the working vim-lsp config I came up with based on [vim-godot](https://github.com/habamax/vim-godot)'s configurations for other lsp clients:

```
if executable('/Applications/Godot.app/Contents/MacOS/Godot')
    au User lsp_setup 
                \ call lsp#register_server({
                \ 'name': 'godot',
                \ 'cmd': ["nc", "localhost", "6008"],
                \ 'root_uri':{server_info->lsp#utils#path_to_uri(
                \    lsp#utils#find_nearest_parent_file_directory(
                \        lsp#utils#get_buffer_path(),
                \        ['godot.project', '.git/']
                \    ))},
                \ 'allowlist': ['gdscript3', 'gdscript']
                \ })
endif
```
[vim-gdscript3](https://github.com/clktmr/vim-gdscript3) creates the 'gdscript3' filetype, but vim-godot uses 'gdscript' so the allowlist includes both.

I'm not sure how to add that to vim-lsp-settings or what the executable would be on other platforms.

**Comment by mattn** [comment]
@prabirshrestha probably, vim-lsp should have this feature with async.vim, right?

**Comment by prabirshrestha** [comment]
Someone would need to send a PR to async.vim.

Related links. 
* https://github.com/prabirshrestha/vim-lsp/pull/928
* https://github.com/prabirshrestha/vim-lsp/issues/469

Would need to support both vim and neovim but someone can send it to which ever one they use first.

Another option is to add proxy support in `efm-langserver` by some sort of flag so vim-lsp talks to efm-langserver via stdio but then efm-langserver talks to godot via sockets or what ever protocol we would need to support.

```yaml
  godot: &godot
    lsp-command: 'godot'
    proxy: 'stdinout<->socket'
```
