### ISSUE TITLE
Allow global settings.json filename full-path definition

### ISSUE THREAD

**Issue by rafi** [mattn/vim-lsp-settings#345]
I'd like to set vim-lsp-settings file without the creating a special directory just for a single `settings.json`.
Currently this is possible:
```vim
let g:lsp_settings_global_settings_dir = $HOME . '/.config/vim-lsp-settings'
```
But I'd _like_ to have it in my vim-config directory:
```vim
let g:lsp_settings_global_settings_path = $HOME . '/.config/nvim/lsp-settings.json'
```
What do you think?

**Comment by mattn** [comment]
Do you want to overwrite settings.json with own?

**Comment by rafi** [comment]
@mattn In other words, why can't I specify the settings filename, and just settings' **directory**?

Currently, I set this:
```viml
let g:lsp_settings_global_settings_dir = $VIM_PATH . '/vim-lsp-settings'
```

But, I have to create a directory for vim-lsp-settings' json:
```
~/.config/nvim
├── autoload/
├── plugin/
├── vim-lsp-settings/
│   └── settings.json
├── coc-settings.json
├── init.vim
└── vimrc
```

I'd like to put my global settings json in my root config, like `coc-settings.json`. Makes sense? :)

**Comment by mattn** [comment]
Because I may add another configuration file or schema file in same directory.

**Comment by rafi** [comment]
I see, thanks for the response.
