### ISSUE TITLE
How to use pyls and pyright-langserver at the same time?

### ISSUE THREAD

**Issue by tamuhey** [mattn/vim-lsp-settings#353]
I installed `pyls` and `pyright-langserver` by `LspInstallServer`, but only `pyls` is enabled.
I can use pyright if I remove `pyls` by `LspUninstallServer`, but I want to use both at the same time.
How to do that?

**Comment by mattn** [comment]
If you want to enable two language servers both, please add below into your vimrc.

```vim
let g:lsp_settings_filetype_python = ['pyls', 'pyright-langserver']
```

**Comment by tamuhey** [comment]
Thank you for your quick reply! Resolved.
