### ISSUE TITLE
pyls intstallation fails on win10

### ISSUE THREAD

**Issue by habamax** [mattn/vim-lsp-settings#38]
I get "The system cannot find the path specified"

![image](https://user-images.githubusercontent.com/234774/71506027-6437c680-2890-11ea-801f-2e23a1b0b073.png)

PS, vim language server and ruby solargraph were successfully installed. 

Thank you for this really convenient plugin!

**Comment by mattn** [comment]
Do you have python3.exe?

**Comment by mattn** [comment]
Could you please try last change?

**Comment by habamax** [comment]
> Do you have python3.exe?

Yes. I actually have python-language server installed manually some months ago with `pip install 'python-language-server[all]'`. 

I just wanted to remove it and use what is provided by this plugin. So what I did is:

1. installed this plugin
2. removed settings from vimrc:
```
" if executable('pyls')
" 	"" pip install 'python-language-server[all]'
" 	au User lsp_setup call lsp#register_server({
" 				\ 'name': 'pyls',
" 				\ 'cmd': {server_info->['pyls']},
" 				\ 'whitelist': ['python'],
" 				\ })
" endif
```

**Comment by mattn** [comment]
Ah, I forgot this. https://github.com/mattn/vim-lsp-settings/pull/25

**Comment by habamax** [comment]
> Could you please try last change?

Didn't help

![image](https://user-images.githubusercontent.com/234774/71506797-6c453580-2893-11ea-803a-2f197935bbe1.png)

**Comment by habamax** [comment]
I have removed all `@echo offs`:

```
C:\Users\maksim.kim\scoop\apps\vim-nightly\current>cd /d C:\Users\maksim.kim\vimfiles\pack\minpac\start\vim-lsp-settings\installer\

C:\Users\maksim.kim\vimfiles\pack\minpac\start\vim-lsp-settings\installer>call pip_install pyls python-language-server

C:\Users\maksim.kim\vimfiles\pack\minpac\start\vim-lsp-settings\installer>if "xpyls" EQU "x" goto :EOF

C:\Users\maksim.kim\vimfiles\pack\minpac\start\vim-lsp-settings\installer>if "xpython-language-server" EQU "x" goto :EOF

C:\Users\maksim.kim\vimfiles\pack\minpac\start\vim-lsp-settings\installer>set server_dir=..\servers\pyls

C:\Users\maksim.kim\vimfiles\pack\minpac\start\vim-lsp-settings\installer>if exist "..\servers\pyls" rd /Q /S "..\servers\pyls"

C:\Users\maksim.kim\vimfiles\pack\minpac\start\vim-lsp-settings\installer>md "..\servers\pyls"

C:\Users\maksim.kim\vimfiles\pack\minpac\start\vim-lsp-settings\installer>cd /d "..\servers\pyls"

C:\Users\maksim.kim\vimfiles\pack\minpac\start\vim-lsp-settings\servers\pyls>where python3  2>NUL
C:\Users\maksim.kim\AppData\Local\Microsoft\WindowsApps\python3.exe

C:\Users\maksim.kim\vimfiles\pack\minpac\start\vim-lsp-settings\servers\pyls>if 0 NEQ 0 (
python3 -m venv ./venv
 venv\bin\pip3 install python-language-server
)  else (
python -m venv ./venv
 venv\bin\pip install python-language-server
)
The system cannot find the path specified.

C:\Users\maksim.kim\vimfiles\pack\minpac\start\vim-lsp-settings\servers\pyls>%~dp0\venv\bin\pyls.cmd %*
 1>pyls.cmd
The system cannot find the path specified.
```

**Comment by habamax** [comment]
Why `bin` is used though?

I can see no `bin` folder in `venv`, all binaries are in `Scripts` folder instead:

![image](https://user-images.githubusercontent.com/234774/71507678-5edd7a80-2896-11ea-9b1f-e781c5e5c51c.png)

**Comment by habamax** [comment]
I have changed `bin` to `Scripts` and was able to half-install the server:

![image](https://user-images.githubusercontent.com/234774/71507938-31450100-2897-11ea-84ca-dffc543a9e28.png)


Not sure what is `pyls.cmd` and where it is copied/made from.

**Comment by johejo** [comment]
Hi, @tsuyoshicho  plans to fix this issue, wait for https://github.com/mattn/vim-lsp-settings/pull/25 .

**Comment by tsuyoshicho** [comment]
Just now total fixing progress...

**Comment by mattn** [comment]
@habamax Where is pyls.cmd ?

```
C:\Users\maksim.kim\vimfiles\pack\minpac\start\vim-lsp-settings\servers\pyls\bin\pyls.cmd
```
?

**Comment by tsuyoshicho** [comment]
@habamax #25 is merged. Please re-try it.

**Comment by habamax** [comment]
@mattn  not sure. I tried to figure out what is going on in the cmd file and there was empty pyls.cmd created somewhere in the path. But I stopped looking into it as soon as I was told the issue is being handling at that moment.

@tsuyoshicho thx, it works now!
