### ISSUE TITLE
s:vimlsp_installer() will return null list, occur error in s:vimlsp_install_server() 

### ISSUE THREAD

**Issue by tsuyoshicho** [mattn/vim-lsp-settings#40]
https://github.com/mattn/vim-lsp-settings/blob/89443bbc2c2f4cedd1f955208f2b181a180dc654/plugin/lsp_settings.vim#L35

It will return [].

Then

```
If you want to enable Language Server, please do :LspInstallServer
function <SNR>61_vimlsp_install_server の処理中にエラーが検出されました:
行    2:
E684: リストのインデックスが範囲外です: 1
```

## Reason:

Open GitHub action YAML file, suggest install server.
But plugin https://github.com/yasuhiroki/github-actions-yaml.vim is activating.
Filetype change to yaml.gha

Key search in `s:vimlsp_installer`

```
function! s:vimlsp_installer() abort
  if !has_key(s:settings, &filetype)
    return []
  endif
```

This will return [].

Error occurred.

## Suggest at resolve:

1. Fix subtype check
2. `s:vimlsp_installer` return null list check process add.

**Comment by mattn** [comment]
You don't have npm right?

**Comment by mattn** [comment]
Fixed in last change. Could you please try it?

**Comment by tsuyoshicho** [comment]
Thanks, I try it.

**Comment by mattn** [comment]
Thank you

**Comment by tsuyoshicho** [comment]
Good it.
