### ISSUE TITLE
Hook to set lsp settings for current buffer

### ISSUE THREAD

**Issue by thomasfaingnaert** [mattn/vim-lsp-settings#42]
Is there a way to set buffer local options only for buffers which have an lsp server running for them?
This is useful to set omnifunc, keywordprg, map keys, ... for lsp buffers, but fall back to default if the server is not installed.

At the moment, I'm using `if executable(...) ...`, but of course, that won't work with LSP servers installed with `vim-lsp-settings`.

Maybe we can add an autocmd that is run whenever a language server is registered for the current buffer?

**Comment by prabirshrestha** [comment]
I have been using this. Readme vim-lsp also mentions this now.

https://github.com/prabirshrestha/vim-lsp/pull/599

**Comment by thomasfaingnaert** [comment]
Oops, can't believe I missed that PR. Thanks!
