### ISSUE TITLE
Why is efm-langserver disabled by default?

### ISSUE THREAD

**Issue by pojiro** [mattn/vim-lsp-settings#422]
It took a bit of time to find out why it wasn't working and enable it.

https://github.com/mattn/vim-lsp-settings/blob/b37de024025cc34ee5f422fcf3638da99851e243/settings.json#L3-L11

**Comment by mattn** [comment]
That's because the experience is very bad. It's a good experience for anyone who knows that efm-langserver is useful. But for those who don't know efm-langserver, it make them confusing.

**Comment by pojiro** [comment]
Thanks for the answer. I noted it.

I use your tools everyday, thank you always.
