### ISSUE TITLE
Option to disable local settings check

### ISSUE THREAD

**Issue by merrilymeredith** [mattn/vim-lsp-settings#440]
I don't really like situations where my editor settings can be changed, or code can be run, just from viewing files in projects.

There's not currently a global setting to disable this check, and I'm happy to make a PR that does only that if that's all you're willing to accept, but additionally I think you might consider either:

- making the local settings check disabled by default, adding a vim global to _enable_ it, or
- limiting what keys are allowed in local settings ("cmd" and probably both config keys are unsafe), or
- confirming with the user first (store confirmed file path + hash somewhere)

**Comment by mattn** [comment]
Have you try `:LspSettingsLocalEdit`?

**Comment by merrilymeredith** [comment]
Sorry, to clarify, I'm aware of this feature, and I'm saying that it is a security concern right now:

```bash
mkdir someproject
chdir $_
mkdir .vim-lsp-settings
cat <<EOF >$_/settings.json
{
  "efm-langserver": {
    "disabled": false,
    "command": "true",
    "cmd": ["perl", "-e", "qx(touch bad.file); 1 while <>"]
  }
}
EOF
view any.file
:q
ls
```

`bad.file`

This is just one simple case of a malicious file someone could clone or pull that takes an unwanted action with no obvious error at the moment it happens.  If `cmd` were disallowed, any language server that accepts an external command to be run through its config would still be a risk.

**Comment by mattn** [comment]
Ah, you are right. it have to be consided. Thanks.

**Comment by mattn** [comment]
How about this idea?

```vim
diff --git a/autoload/lsp_settings/profile.vim b/autoload/lsp_settings/profile.vim
index d7cecfe..ed44cdd 100644
--- a/autoload/lsp_settings/profile.vim
+++ b/autoload/lsp_settings/profile.vim
@@ -59,9 +59,13 @@ function! lsp_settings#profile#load_local() abort
     if !filereadable(l:root . '/settings.json')
       return
     endif
+    let l:deny_keys = get(g:, 'lsp_settings_deny_local_keys', ['cmd'])
     let l:settings = json_decode(join(readfile(l:root . '/settings.json'), "\n"))
     if has_key(g:, 'lsp_settings')
       for [l:k, l:v] in items(l:settings)
+        if index(l:deny_keys, l:k)
+          continue
+        endif
         if has_key(g:lsp_settings, l:k)
           let g:lsp_settings[l:k] = s:extend(g:lsp_settings[l:k], l:v)
         else
@@ -69,6 +73,9 @@ function! lsp_settings#profile#load_local() abort
         endif
       endfor
     else
+      for l:k in keys(l:deny_keys)
+        call remove(l:settings, l:k)
+      endfor
       let g:lsp_settings = l:settings
     endif
   catch
```

**Comment by mattn** [comment]
Ah, this is still wrong.

**Comment by mattn** [comment]
Addressed in https://github.com/mattn/vim-lsp-settings/pull/441

**Comment by mattn** [comment]
Thank you!
