### ISSUE TITLE
Any way to pass only extra arguments for server executables?

### ISSUE THREAD

**Issue by s417-lama** [mattn/vim-lsp-settings#460]
As far as I know, setting the whole command line is the only way to specify extra arguments for server executables (e.g., `clangd`).
However, if language servers are installed automatically, we basically don't know where server executables are installed.

After some investigations, I found the installation path and I could specify extra arguments correctly as shown below,
```vim
  let g:lsp_settings = {
        \   'clangd': {
        \     'cmd': [$HOME . '/.local/share/vim-lsp-settings/servers/clangd/bin/clangd', '--header-insertion=never']
        \   },
        \ }
```

but I prefer to have something like `args` option in addition to `cmd` option.

FYI; I wanted to set `--header-insertion=never` option to `clangd` to disable annoying automatic insertion of C/C++ header include directives.

**Comment by mattn** [comment]
Yes, right. FYI, you can do it with `export CLANGD_FLAGS=--header-insertion=never`.

**Comment by mattn** [comment]
Is this you expected?
```diff
diff --git a/settings/clangd.vim b/settings/clangd.vim
index 27f53cd..b0e9814 100644
--- a/settings/clangd.vim
+++ b/settings/clangd.vim
@@ -2,7 +2,7 @@ augroup vim_lsp_settings_clangd
   au!
   LspRegisterServer {
       \ 'name': 'clangd',
-      \ 'cmd': {server_info->lsp_settings#get('clangd', 'cmd', [lsp_settings#exec_path('clangd')])},
+      \ 'cmd': {server_info->lsp_settings#get('clangd', 'cmd', [lsp_settings#exec_path('clangd')]+lsp_settings#get('clangd', 'args', []))},
       \ 'root_uri':{server_info->lsp_settings#get('clangd', 'root_uri', lsp_settings#root_uri('clangd'))},
       \ 'initialization_options': lsp_settings#get('clangd', 'initialization_options', v:null),
       \ 'allowlist': lsp_settings#get('clangd', 'allowlist', ['c', 'cpp', 'objc', 'objcpp']),
```

**Comment by s417-lama** [comment]
Yes, exactly.

**Comment by mattn** [comment]
Thank you
