### ISSUE TITLE
typescript-language-server: not running

### ISSUE THREAD

**Issue by kresdjan** [mattn/vim-lsp-settings#471]
I have installed both `prabirshrestha/vim-lsp'` and `mattn/vim-lsp-settings` plugins. Cloned them into `~/.vim/pack/plugins/start`.  

I have installed a few language servers after getting prompted to run `LspInstallServer` when opening a file (👍 really awesome, thanks.) I got that prompt for `html`, `css ` and `json`, but not for `.js` or `.ts` files. 

I then ran `LspInstallServer` to install the `typescript-language-server` manually. No errors in the log. The typescript-language-server seems be installed correctly into `~/.local/share/vim-lsp-settings/servers/typescript-language-server`.

```json
{
  "name": "",
  "dependencies": {
    "typescript": "^4.4.3",
    "typescript-language-server": "^0.6.2"
  }
}
```

Restarted vim. Still when opening either `.js` or `.ts` file the server isn't running. `LspStatus: typescript-language-server: not running`. I've tried uninstalling and reinstalling. Same. I don't know if It can't locate the binary. Or what the issues. Maybe (quite possibly I'm missing a configuration step).

Does anyone else have this issue?

**Comment by brianjamesquinn1** [comment]
I've also run into this. @kresdjan or @Syndamia did you have solutions?

**Comment by Syndamia** [comment]
Sorry to be that guy, but I stopped using `vim-lsp`. Last I remember, I never figured out a solution/workaround.

**Comment by major-winter** [comment]
I'm also facing this problem. Sometimes the `typescript-language-server` works perfectly, but sometimes it doesn't.
