### ISSUE TITLE
Nim Language Server Fails To Install

### ISSUE THREAD

**Issue by miversen33** [mattn/vim-lsp-settings#485]
When attempting to install the nim language server on linux, it fails with the following error
```
permission denied: $HOME/.local/share/nvim/plugged/vim-lsp-settings/installer/install-nimlsp.sh 
```

Upon inspection of `install-nimlsp.sh`, it appears this shell script is not executable and thus cannot be executed by the installer. 

Please make this shell script [install-nimlsp.sh](https://github.com/mattn/vim-lsp-settings/blob/master/installer/install-nimlsp.sh) executable

If needed, I can submit a PR for this, however this seems simple enough that it shouldn't be needed.

Thank you for the great plugin!

**Comment by mattn** [comment]
Thanks. Fixed.
