### ISSUE TITLE
Restrict or remove `remark-language-server`

### ISSUE THREAD

**Issue by halostatue** [mattn/vim-lsp-settings#543]
After extensive discussion, I believe that it is a _mistake_ that `remark-language-server` has been added to `vim-lsp-settings` as a "markdown" language server. The maintainers there do not seem to be interested in supporting the use case of "people who use markdown", but instead are exclusively interested in supporting the use case of "people who use remark".

See: https://github.com/remarkjs/remark/discussions/960

I believe that the correct answer for this is to _either_ prevent `remark-language-server` from being suggested as a language server for markdown (instead only doing so if both markdown _and_ remark configuration minimums have been matched, e.g., https://github.com/neovim/nvim-lspconfig/pull/1641). If that particular complexity cannot be met, then I recommend that `remark-language-server` be _removed_ from `vim-lsp-settings` because it is not fit for the purpose of being a language server for markdown without opting into the entire `remark` ecosystem.

It should only be reconsidered for expansion if they change their stance, which I have no reason to believe will happen based on the discussion noted above. As it is, the suggested installation of `remark-language-server` is a misleading option _at best_ with the current settings.

**Comment by ChristianMurphy** [comment]
`remark-language-server` is general purpose, and, like several other language servers in `vim-lsp-settings`, it requires some configuration to use.

There are a number additional viable options outlined in https://github.com/remarkjs/remark/discussions/960#discussioncomment-2270454 and https://github.com/remarkjs/remark/discussions/960#discussioncomment-2279236
Discussion on improvement to the language server is still open, the current stall on this particular discussion is due to hostility from @halostatue.

**Comment by halostatue** [comment]
No, the stall is because `remark-language-server` is advertised in `vim-lsp-settings` as something that it isn’t. It _isn’t_ a markdown language server. It _only_ works you are in a project that is based on `remark`. As it does not appear (see #545) that `vim-lsp-settings` and/or `vim-lsp` perform _conditional_ installation/activation based on the presence of the node-cruft which is `remark`, it should _not_ be advertising itself as a markdown language server.

As such, it should be restricted (to _not_ be advertised as a markdown language server), removed (my preference, given the obtuseness presented by `remark` developers), or `vim-lsp-settings` and/or `vim-lsp` should be enhanced to make it so that `remark-language-server` is only presented as an option to anyone who has opted into the whole `remark` ecosystem.

It is, IMO, a bug in `vim-lsp-settings` to present a language server that requires specific _project_ configuration to work for a filetype. That may include things like the `eslint-language-server`, which seems to only work in a whole node-supported project and not when editing "random" JavaScript files (fortunately, the `deno-language-server` appears to do what one would expect from that when _not_ in a project).
