### ISSUE TITLE
`:LspStatus` returns `typescript-language-server: not running`

### ISSUE THREAD

**Issue by ando-masaki** [mattn/vim-lsp-settings#547]
Why `:LspStatus` returns `typescript-language-server: not running` ?
Please show me how to run `typescript-language-server`.

```
$ vim helloworld.ts
:PlugInstall
:LspInstallServer
:LspStatus
typescript-language-server: not running
```

**Comment by mattn** [comment]
Your root directory have node_modules?

**Comment by mattn** [comment]
Installation had succeeded?

**Comment by ando-masaki** [comment]
Probably, installation had succeeded.
<img width="1280" alt="スクリーンショット 2022-03-09 13 48 08" src="https://user-images.githubusercontent.com/4375029/157374812-5883887a-0b3c-4503-923c-0ed1feb2a7a5.png">

**Comment by ando-masaki** [comment]
I'm sorry. It worked when I added following settings on `~/.vimrc`.

```
let g:lsp_diagnostics_echo_cursor = 1
let g:lsp_settings = {
\ 'efm-langserver': {
\   'disabled': v:false
\ },
\ }

autocmd BufWritePre *.ts,*.tsx call execute('LspDocumentFormatSync --server=efm-langserver')
```
