### ISSUE TITLE
install omnisharp gets error on windows 10

### ISSUE THREAD

**Issue by SamL1n** [mattn/vim-lsp-settings#548]
I've searched all the issues about installation errors,but it still can't solve my problem.

vim version: 8.2
OS: windows 10

I run `:LspInstallServer`  to install omnisharp.
the chinese below means that `it should not exist` 

![image](https://user-images.githubusercontent.com/59719285/158109829-decab4f3-e6ec-4b19-8e8a-839ebe4ab97b.png)

**Comment by mattn** [comment]
```
where unzip
echo %ERRORLEVEL%
```
What number do you get?

**Comment by SamL1n** [comment]
> 

1

**Comment by SamL1n** [comment]
\Vim\plug-vim\vim-lsp-settings\installer\install-omnisharp-lsp.cmdERRORLEVEL!C:\Program was unexpected at this time.

Shell return 1

**Comment by SamL1n** [comment]
> ```
> where unzip
> echo %ERRORLEVEL%
> ```
> 
> What number do you get?

I found that whatever I run ,always return 1
`:!echo %ERRORLEVEL%` return 1 
`:!echo %asdfasdfaf%`  return 1 

maybe I misunderstood you,can you tell more details?
Thanks!

**Comment by mattn** [comment]
Are you using powershell? It should be done on cmd.exe

**Comment by SamL1n** [comment]
> Are you using powershell? It should be done on cmd.exe

yes,I use powershell.
cmd? okay, i have a try.

**Comment by SamL1n** [comment]
> Are you using powershell? It should be done on cmd.exe

![image](https://user-images.githubusercontent.com/59719285/158130761-5106aca6-d764-4e8a-9273-bc4cbb78c2c7.png)

it seems like that cmd has the same problem.
I don't know how to debug this problem.

**Comment by mattn** [comment]
As far as I can see the installer, where command should return 0 if the unzip.exe is found.

https://github.com/mattn/vim-lsp-settings/blob/d9a4a69b76af3a52edb9bf627213b73902eb02a6/installer/run_unzip.cmd#L5

**Comment by SamL1n** [comment]
> As far as I can see the installer, where command should return 0 if the unzip.exe is found.
> 
> https://github.com/mattn/vim-lsp-settings/blob/d9a4a69b76af3a52edb9bf627213b73902eb02a6/installer/run_unzip.cmd#L5

![image](https://user-images.githubusercontent.com/59719285/158132594-eef763ac-5716-43cb-a636-6a84634cb4d7.png)

i got you
the command `%ERRORLEVEL%` return 0

**Comment by SamL1n** [comment]
i changed the `run_unzip.cmd` as below
```
@echo off

if "x%1" equ "x" goto :EOF


unzip %*

```
Now it has been installed successfully!

**Comment by SamL1n** [comment]
so,let's take a look.
1、I have unzip.exe on my computer
2、However,the code `if %ERRORLEVEL% equ 0`  seems like return a `false`,which is out of expectation.

**Comment by SamL1n** [comment]
here is test.cmd
```cmd
where unzip 2>NUL
if %ERRORLEVEL% equ 0 (
    echo "find unzip!"
) else (
    echo "no unzip!"
)
```

return "find unzip!" 

So the code is right.And i can't figure out the installation problem.
All in all,thank you for replying!
@mattn
