### ISSUE TITLE
Disable rust-analyzer autoimport.

### ISSUE THREAD

**Issue by tnull** [mattn/vim-lsp-settings#572]
I'm trying to disable the autoimport feature of rust analyzer, because I'd like to have full control when which imports change.

To this end, I set the following lsp_settings in the vimrc:
```vim
let g:lsp_settings = { 'rust-analyzer': { 'initialization_options': { 'completion': { 'autoimport': { 'enable': v:false }, }, }, }, }
```

However, the autoimport seems to be still enabled: when browsing through autocompletion choices with Ctrl-n, I still see entries such as
```
ASDF (use super::asdf::ASDF)    struct     [lsp]
```
and when I select them, the line `use super::asdf::ASDF` is added to the beginning of the file.
The first half is technically exactly what I want, i.e., still being able to browse definitions from all over the project. However, I'd like to add the import on my own.

Have I misconfigured this or does `vim-lsp-settings` simply ignore my override?
What can I do to get the expected result?

**Comment by mattn** [comment]
As far as I see the [documentation](https://rust-analyzer.github.io/manual.html#configuration), it seems to be right.

**Comment by tnull** [comment]
> As far as I see the [documentation](https://rust-analyzer.github.io/manual.html#configuration), it seems to be right.

Hm, I can also confirm that if I hardcode the default value in `settings/rust-analyzer.vim` to `v:false`, the autoimport seems to be disabled. This is better than before, but sadly now the entries that would have been autoimported before are simply not shown.

However, that means that either my override is wrong, or `vim-lsp-settings` doesn't take it into accout. Is there anything I can do to figure out which it is?

**Comment by tnull** [comment]
Yeah, kind of tried that in `vimrc` before I went to the solution above. Tried again: output is `{}`, but afterwards the autoimport is still in effect.

**Comment by mattn** [comment]
If you set `g:lsp_settings` correctly, you should see the value you did set.

![screenshot](https://user-images.githubusercontent.com/10111/169345457-359326b8-20e0-4099-ba70-c56852e3081c.gif)
