### ISSUE TITLE
vim-lsp-settings/installer/install-clangd.sh: 54: ubuntu_version: not found

### ISSUE THREAD

**Issue by MiyataYuya** [mattn/vim-lsp-settings#599]
Hello,

I'm using vim 8.1 on Ubuntu20.04.
I ran the :LspInstallServer command to install clangd.
The following is the output.
```
/usr/bin/lsb_release
/home/miyata/.vim/plugged/vim-lsp-settings/installer/install-clangd.sh: 54:     ubun
tu_version: not found
```
I'm not too sure but I think the line 54 in /vim-lsp-settings/installer/install-clangd.sh should be commented out.
By commenting it out, I was able to install it without any problems.

**Comment by mattn** [comment]
Closed by https://github.com/mattn/vim-lsp-settings/pull/597
