### ISSUE TITLE
Could not find an installable clangd release

### ISSUE THREAD

**Issue by 41337** [mattn/vim-lsp-settings#626]
![Captura de tela de 2022-10-09 19-08-45](https://user-images.githubusercontent.com/88632118/194781759-381941e1-234e-4e8b-aed5-defae6aa56a6.png)

**Comment by heckenscherenmann** [comment]
How did you fix this? Same issue here, tested on 2 machines so far

**Comment by 0x41337** [comment]
@heckenscherenmann I forgot about this problem a long time ago but I believe I adjusted the paths and it worked ?
