### ISSUE TITLE
ESLint?

### ISSUE THREAD

**Issue by Vanuan** [mattn/vim-lsp-settings#64]
There's a LSP server for ESLint:  
https://www.npmjs.com/package/eslint-server

Is is possible to make it work with vim?

**Comment by wordijp** [comment]
typescript-language-server supported ESLint/TSLint by plugins:
theia-ide/typescript-language-server#58
theia-ide/typescript-language-server#73

and, found ESLint plugin:
https://github.com/Quramy/typescript-eslint-language-service

Example usage in semicolon test case.

files

```
.
├── main.js
├── tsconfig.json
└── .eslintrc.yml
```

Intall node_modules

```
$ # `typescript` need install, hmm.
$ npm init -y
$ npm install \
  eslint \
  typescript \
  typescript-eslint-language-service \
  @typescript-eslint/parser \
  @typescript-eslint/typescript-estree
```

main.js

```javascript
const message = 'hello';
console.log(message) // error
```

tsconfig.json

```json
{
  "compilerOptions": {
    "allowJs": true,
    "plugins": [
      {
        "name": "typescript-eslint-language-service"
      }
    ]
  }
}
```

.eslintrc.yml

```yaml
parser: "@typescript-eslint/parser"
rules:
  semi: error
```

**Comment by mattn** [comment]
If you want to enable eslint always on typescript-language-server, you can specify `plugin` for `initialization_options` like @wordijp's comment.

**Comment by Vanuan** [comment]
What if my eslint config is named `.eslintrc.json`?

**Comment by wordijp** [comment]
Just replace yaml to json.

.eslintrc.json

```json
{
  "parser": "@typescript-eslint/parser",
  "rules" : {
    "semi": "error"
  }
}
```

**Comment by Vanuan** [comment]
Apparently, it needs the dependencies to be installed locally. I had typescript-language-server installed globally, so I thought global install would work.

**Comment by Vanuan** [comment]
Ok, the issue was that I already had `eslint@6.7.2` installed. `yarn add eslint` added version `^6.7` which is resolved to `6.8.0` and is incompatible.

**Comment by Vanuan** [comment]
Thanks. Lessons learned:

1. Make sure `eslint` command works and produces errors
2. make sure to install `typescript-eslint-language-service` locally instead of globally
3. add `typescript-eslint-language-service` to `tsconfig.json` plugins
4. make sure `@typescript-eslint/parser` parser is used for `*.ts` files

Small question: is there any noticeable difference between `typescript-eslint-language-service` and `vscode-eslint`? That is, would VSCode user notice the difference?

**Comment by wordijp** [comment]
I checked each language server system.
I think the user experience depends on each editor, It seems that there is no difference in Linter result.
Because both are plugins that bridge the language server and eslint.
`vscode-lint` bridges `vscode-languageserver` and `eslint`.
`typescript-eslint-language-server` bridges `typescript-language-server` plugin and `eslint`.

Supplementary information: please see `typescript-eslint-language-service` author's slide, `slide=17` is system image page.
https://quramy.github.io/ts-eslint-talk/#slide=17

**Comment by Vanuan** [comment]
So `typescript-eslint-language-service` requires `typescript-language-server`? It seemed to work without it.

**Comment by Vanuan** [comment]
Anyway, I got it running, thank you for help!
