### ISSUE TITLE
bug: vim-lsp sends encoded URI, but deno lsp returns raw URI

### ISSUE THREAD

**Issue by 4513ECHO** [mattn/vim-lsp-settings#648]
## Description

For `deno lsp`, `vim-lsp` and `vim-lsp-settings` sends URI as encoded like `@` → `%40`.
But `deno lsp` returns response with non-encoded URI.
So diagnostics are never shown even there is error in file.

## How to reproduce

Start vim with below `.vimrc` and open below example file.

- [vimrc file](https://gist.github.com/4513ECHO/3f1ec8916e2c9a3bf4bf7c66b94b608a)
- [example file](https://gist.github.com/4513ECHO/a3e0801f69428e2dc39c0170a593e169)
- [log file](https://gist.github.com/4513ECHO/78ee37fb3904f5e1099929de19bcc5ec)

**Comment by mattn** [comment]
This conversion is not a part of vim-lsp-settings. It is in vim-lsp.
I opened pull-request for vim-lsp.

https://github.com/prabirshrestha/vim-lsp/pull/1403

However, at least, deno lsp should escape `[]`. `file:///home/hibiki/dotfiles/config/nvim/@%5Btest%5D.ts` is true.
