### ISSUE TITLE
:LspInstallServer not an editor command

### ISSUE THREAD

**Issue by tmpm697** [mattn/vim-lsp-settings#76]
I have all required plugins installed, but when issue `LspInstallServer` I got the error `not an editor command`.

Archlinux / vim-git latest (via aur), install plugin using native vim8 method

**Comment by mattn** [comment]
What the filetype did you open?

**Comment by tmpm697** [comment]
> What the filetype did you open?

With empty buffer.

With rust file (.rs) I got this error:
```
Error detected while processing function <SNR>54_vimlsp_install_server:
line    3:
E684: list index out of range: 0
```

**Comment by mattn** [comment]
Ah, the error is a bug. And fixed in last change. However, your buffer does not have filetype with the .rs file.

**Comment by mattn** [comment]
BTW, LspInstallServer command can not be used for empty buffer since  vim-lsp-settings does not know which server should be installed.

**Comment by tmpm697** [comment]
nice, thanks. but I search through $HOME and I seem can't find `/.server` folder that contain server, I installed golang server via `:LspInstallServer`

**Comment by mattn** [comment]
gopls should be located at `~/.vim/plugged/vim-lsp-settings/servers/gopls/gopls` if you use vim-plug.

**Comment by tmpm697** [comment]
nice, thanks. I use native vim8 way to manage plugins so it's in `/home/sugar/.vim/pack/default/start/vim-lsp-settings/servers/gopls/gopls`

**Comment by tmpm697** [comment]
nice, thanks. I use native vim8 way to manage plugins so it's in `~/.vim/pack/default/start/vim-lsp-settings/servers/gopls/gopls`
