### ISSUE TITLE
[Question] Is there a way to reliably recall the executable files installed by the installer?

### ISSUE THREAD

**Issue by mikoto2000** [mattn/vim-lsp-settings#777]
Is there a way to reliably recall the executable files installed by the installer?
(* not the executable in the path)

I try `:LspInstallServer rust-analyzer`, but rustup's default install rust is put dummy `rust-analyzer` in PATH.
(See: https://github.com/rust-lang/rustup/issues/3846)

So, vim-lsp will also occur the following error.

```
error: Unknown binary 'rust-analyzer' in official toolchain 'stable-xxxx'.
To install, run `rustup component add rust-analyzer`.
```

`lsp_settings#exec_path('rust-analyzer')` is first search PATH environment.

https://github.com/mattn/vim-lsp-settings/blob/02cd145c223ddf1dfb3069303400946d1907ccec/settings/rust-analyzer.vim#L5

https://github.com/mattn/vim-lsp-settings/blob/02cd145c223ddf1dfb3069303400946d1907ccec/autoload/lsp_settings.vim#L225

Can I call executable without PATH environment?

**Comment by mikoto2000** [comment]
Thank you for your comment.
I understood install(put a PATH location) rust-analyzer single binary to be can running lsp.

However, I was concerned that the installed binary of vim-lsp-setting might not be used (highly).
For example, rust-analizer is placed as a single binary with `install-rust-analizer.(sh|cmd)`, but if there is a binary with the same name on the path, it will not be used. (This resulted in the creation of this issue.)

Shouldn't we prioritize the ones installed via the installer over the ones on the path?

**Comment by mattn** [comment]
Then, you should uninstall the binary `LspUninstallServer rust-analyzer`. vim-lsp-settings should use the executable found in the PATH.

**Comment by mikoto2000** [comment]
Sorry, I'm confused.

I thought vim-lsp-settings was designed to use binaries installed with install-xxx.(sh|cmd).
Are the binaries installed by the installer not used?

I thought it was designed to first look for PATH, and if it wasn't found in PATH, it would use the binary installed by the installer.
I thought it would be better to prioritize what the installer installed.

† I'd like to talk about the design of vim-lsp-settings, not just rust-analyzer.


I'm sorry, I can't write in English well, so I will write in Japanese.

vim-lsp-settings は、 PATH にあるか探し、 PATH に無ければインストーラーがインストールしたバイナリを実行するものだと思っていました。
そうであれば、(インストーラーを作った時に動作確認したであろう、)インストーラーがインストールしたバイナリを使う方が問題が少なくなるのではと思いました。

**Comment by mattn** [comment]
作っておいてアレなんですが、たしかインストーラが使われていたらそちらを、無ければパス内のものを、という動きにしていた気がしています。

**Comment by mikoto2000** [comment]
あれ？そうなのですか、私の勘違いでしたか。もう一度挙動とソースを確認してみます。
コメントありがとうございます。

**Comment by mikoto2000** [comment]
間違えて閉じてしまいました...

確認したところ、初期実装(？)の頃から「まず PATH を探して、無ければ `g:lsp_settings_servers_dir` から探す」という順序になっているようでした。


■ 現在の実装

PATH, `g:lsp_settings_extrapaths` の両方に無い場合、インストールされたものを使う実装。

https://github.com/mattn/vim-lsp-settings/blob/02cd145c223ddf1dfb3069303400946d1907ccec/autoload/lsp_settings.vim#L225-L269


■ 初期(？)実装

PATH から探す処理の後ろに追加する形で初期(？)実装が行われている。

https://github.com/mattn/vim-lsp-settings/commit/fef383ee4daca1b856d7f001b6696bb210a1442c#diff-d7bcd9bf24c66b67490ed72182bce5de4a813ddbdd141d1fa21511bf8b5ee981R19

https://github.com/mattn/vim-lsp-settings/blob/fef383ee4daca1b856d7f001b6696bb210a1442c/autoload/lsp_settings.vim

**Comment by mikoto2000** [comment]
本来の優先順位としては、 「インストールされたもの > `g:lsp_settings_extra_paths` のもの > PATH 内のもの」という感じでしょうか？

**Comment by mattn** [comment]
LspSettingsGlobalEdit で cmd を直接パス指定するのではだめでしょうか？

**Comment by mattn** [comment]
例えばこういう感じに。
![image](https://github.com/user-attachments/assets/1080939b-5575-4945-b5d2-b495401944a9)

**Comment by mikoto2000** [comment]
せっかくインストールしたものが使われないのがもったいないと思いましたが、こういう状況になるのは rust-analyzer くらいですかね。

それを考えると確かに設定や環境でカバーするほうが良いと思えてきました。
cmd のパス指定を試してみます！ありがとうございます！
