### ISSUE TITLE
lsp4xml format options not working

### ISSUE THREAD

**Issue by ranebrown** [mattn/vim-lsp-settings#88]
Using the below settings with the lsp4xml server does not seem to be working correctly. Looking at the logs it looks like the true/false values are wrapped in quotes (which is necessary in the vim setting) but the quotes should be removed when passed to the server. That is my guess at least.

```vim
    let g:lsp_settings = {
    \  'lsp4xml':{
    \    'initialization_options':{
    \       'settings':{
    \         'format': {
    \           'splitAttributes': 'true',
    \           'spaceBeforeEmptyCloseTag':'false',
    \         }
    \       }
    \    }
    \  },
    \}

```

**Comment by ranebrown** [comment]
Changed the true false values to `v:true` and `v:false` which now looks correct in the log but the settings don't seem applied. Any help would be appreciated.

**Comment by mattn** [comment]
As far as I looked code of lsp4xml, your configuration lost `xml` block.

```vim
    let g:lsp_settings = {
    \  'lsp4xml':{
    \    'initialization_options':{
    \       'settings':{
    \         'xml':{
    \           'format': {
    \             'splitAttributes': 'true',
    \             'spaceBeforeEmptyCloseTag':'false',
    \           }
    \         }
    \       }
    \    }
    \  },
    \}
```

**Comment by ranebrown** [comment]
Thanks!
