### ISSUE TITLE
vimlsp_settings_suggest() doesn't work on elixir file(*.ex, *.exs)

### ISSUE THREAD

**Issue by pojiro** [mattn/vim-lsp-settings#92]
OS: linux
vim: version 8.0.1453

When I open other filetype like *.c, *.cpp, the function works.

**Comment by mattn** [comment]
What do you get with `:set ft?`

```
:e foo.ex
:set ft?
:e foo.exs
:set ft?
```

**Comment by mattn** [comment]
Do you install elixir-editors/vim-elixir ?

**Comment by pojiro** [comment]
I got below filetype.

> `:e foo.ex`
> `:set ft?`

`  filetype=euphoria3`

> `:e foo.exs`
> `:set ft?`

`  filetype=`

**Comment by pojiro** [comment]
> Do you install elixir-editors/vim-elixir ?

No, I don't.
So I installed it, and tried `:e foo.ex`, the function works! Thanks for your quick reply.

Did I miss any documentation?

**Comment by mattn** [comment]
Most of users don't read documentation. I'm trying to show suggestion for installing vim-plugins

https://github.com/mattn/vim-lsp-settings/pull/93
